"""
Create Route model

Revision ID: 2076dd5362af
Revises: 9a2b51bf00df
Create Date: 2022-08-31 23:50:57.465965

"""
import sqlalchemy as sa
from alembic import op


revision = "2076dd5362af"
down_revision = "9a2b51bf00df"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "route",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=6), nullable=False),
        sa.Column("number_prefix", sa.String(length=4), nullable=False),
        sa.Column(
            "type",
            sa.Enum("Bus", "Trolley", "Tram", "Minibus", name="type"),
            nullable=False,
        ),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company_route",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["route.id"],
        ),
        sa.PrimaryKeyConstraint("company_id", "route_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_route")
    op.drop_table("route")
    # ### end Alembic commands ###
