query {
  cities {
    count
    edges {
      node {
        id
        name
        abbreviation
        geobounds {
          minLat
          minLon
          maxLat
          maxLon
        }
      }
    }
  }
}
