query {
  cities {
    edges {
      node {
        id
        companies {
          count
          edges {
            node {
              id
            }
          }
        }
      }
    }
  }
}
